{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wg-easy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wg-easy.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.vpn }}
      targetPort: udp-vpn
      protocol: UDP
      name: udp-vpn
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort.vpn }}
      {{- end }}
    - port: {{ .Values.service.port.ui }}
      targetPort: http-ui
      protocol: TCP
      name: http-ui
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort.ui }}
      {{- end }}
  selector:
    {{- include "wg-easy.selectorLabels" . | nindent 4 }}
{{- end }}
